# Generated by Django 5.1.4 on 2025-01-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_category_slug_recipe_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
