# Generated by Django 5.1.4 on 2025-01-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                default="recipes/images/default-recipe.jpg",
                null=True,
                upload_to="recipes/images/",
            ),
        ),
    ]
