# Generated by Django 5.1.4 on 2025-01-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_recipeimage_is_main_image_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeimage",
            name="step_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
